baseURL = "https://gn.shoogle.net/guinea"
languageCode = "fr"
title = "Guinea"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "guinea"

[taxonomies]
  shop = "shops"
